Data Analytics III

1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#df = sns.load_dataset('iris')
df = pd.read_csv('Dataset/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [5]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
df.shape

(150, 6)

In [8]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [9]:
x = df.drop('Species',axis=1)
y = df['Species']

# x: The feature matrix that contains all columns except the target variable 'Species'. It includes attributes like SepalLengthCm, SepalWidthCm, etc. y: The target variable (Species), which contains the class labels (e.g., 'setosa', 'versicolor', 'virginica').

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)
print(x_train.shape)

# train_test_split(): Splits the data into training and testing sets. x_train, y_train: Feature matrix and target for training. x_test, y_test: Feature matrix and target for testing. test_size=0.2: Specifies that 20% of the data will be used for testing, and the remaining 80% will be used for training. random_state=40: Ensures that the split is reproducible (same every time the code runs). print(x_train.shape): Prints the shape of the training set (x_train), showing how many features are in the training data.

(120, 5)


In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

# GaussianNB(): Initializes the Naïve Bayes classifier, specifically the Gaussian Naïve Bayes model. model.fit(x_train, y_train): Trains the model on the training data (x_train, y_train).

GaussianNB()

In [12]:
y_pred = model.predict(x_test) # model.predict(x_test): Uses the trained model to make predictions on the test data (x_test).
print(y_pred)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor']


In [13]:
from sklearn.metrics import confusion_matrix,recall_score,precision_score,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

# confusion_matrix(): Computes the confusion matrix, which compares the predicted values (y_pred) against the actual values (y_test). print(cm): Prints the confusion matrix, which contains four values: True Positives (TP): Correctly predicted positive instances. False Positives (FP): Incorrectly predicted as positive. False Negatives (FN): Incorrectly predicted as negative. True Negatives (TN): Correctly predicted negative instances.

[[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]


In [14]:
accu = accuracy_score(y_test,y_pred) # Computes the accuracy of the model, which is the proportion of correct predictions (i.e., TP + TN) to total predictions.
print(accu)

1.0


In [15]:
error = 1-accu # Calculates the error rate, which is the complement of the accuracy (1 - accuracy).
print(error)

0.0


In [16]:
rec = recall_score(y_test,y_pred,average="macro") # recall_score(): Computes the recall (True Positive Rate) for the test set. It calculates the proportion of actual positives that are correctly identified. average="macro": Averages recall across all classes.
print(rec)


1.0


In [17]:
n = cm.shape[0] # Gets the number of classes from the confusion matrix (in this case, it will return 3 because there are 3 species in the dataset).
print(n)

3


In [18]:
for i in range (n):
    tp = cm[i,i]
    fp = cm[:,i].sum()-tp
    fn = cm[i,:].sum()-tp
    tn = cm.sum()-(tp+fp+fn)
    print(f"tp={tp},fp={fp},fn={fn},tn={tn}")

# For each class (3 classes in total): TP (True Positives): The diagonal element cm[i, i] of the confusion matrix. FP (False Positives): The sum of the column cm[:, i], minus the TP. FN (False Negatives): The sum of the row cm[i, :], minus the TP. TN (True Negatives): The total sum of the confusion matrix, minus the TP, FP, and FN. This loop calculates and prints the values of TP, FP, FN, and TN for each class.

tp=8,fp=0,fn=0,tn=22
tp=12,fp=0,fn=0,tn=18
tp=10,fp=0,fn=0,tn=20
